cache-max-age 0s
max-ttl 5s
mdns all
bogus-priv true
debug false
listen localhost:5053
profile xxxxxx
use-hosts true
timeout 5s
control /var/run/nextdns.sock
cache-size 10MB
detect-captive-portals false
max-inflight-requests 256
log-queries false
report-client-info true
discovery-dns 
hardened-privacy false
setup-router false
auto-activate false
